services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - VERSION=docker
#      - PLEX_CLAIM= #optional
      - PLEX_ARCH=amd64
    volumes:
      - /mnt/Docker/Plex/library:/config
      - /mnt/plex/films:/films
      - /mnt/plex/muziek:/muziek
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"      
    restart: unless-stopped