services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - VERSION=docker
#      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/Docker/Plex/library:/config
      - /mnt/plex/films/Films:/mnt/plex/films
      - /mnt/plex/muziek:/mnt/plex/muziek
    restart: unless-stopped