services:
  wud:
    image: ghcr.io/fmartinou/whats-up-docker
    container_name: wud
    ports:
      - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/Docker/WUD/config:/etc/wud/config:ro  # Optioneel: voor aangepaste configuratiebestanden
    environment:
#      - WUD_AUTH_BASIC_USER=${WUD_USERNAME}
#      - WUD_AUTH_BASIC_HASH=${WUD_PASSWORD_HASH}
      - WUD_TRIGGER_DOCKER_CONTAINER_LABELS=true
      - WUD_TRIGGER_DOCKER_SWARM_SERVICES=false
      - WUD_TRIGGER_DOCKER_DOCKER_COMPOSE_FILES=false
        ## Trigger DOCKER-COMPOSE
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_FILE=/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_PRUNE=true  
        ## Cron Job    
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *   
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true  
      - WUD_TRIGGER_DOCKER_LOCAL_AUTO=false  
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - TZ=Europe/Amsterdam
        ## MQTT
      - WUD_TRIGGER_ENABLED=mqtt
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://192.168.110.10:1883
      - WUD_TRIGGER_MQTT_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_HASS_DISCOVERY=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_CLIENTID=wud
      - WUD_TRIGGER_MQTT_MOSQUITTO_USER=wud
      - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=MYPASSWORD      

    restart: always

