services:
  spotweb:
    image: jgeusebroek/spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
     - PUID=1000
     - GUID=1000
     - TZ=Europe/Amsterdam
     - SPOTWEB_DB_TYPE=$DB_TYPE
     - SPOTWEB_DB_HOST=spotweb_db
     - SPOTWEB_DB_PORT=3306
     - SPOTWEB_DB_NAME=spotweb
     - SPOTWEB_DB_USER=spotweb
     - SPOTWEB_DB_PASS=$MYSQL_PASSWORD
     - "SPOTWEB_CRON_RETRIEVE=* */2 * * *"
    depends_on:
     - spotweb_db
    ports:
     - 8882:80
    volumes:
     - /mnt/Docker/Spotweb/config:/config

  spotweb_db:
    image: linuxserver/mariadb
    container_name: spotwebdb
    restart: unless-stopped
    environment:
     - PUID=1000
     - PGID=1000
     - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
     - TZ=Europe/Amsterdam
     - MYSQL_DATABASE=spotweb
     - MYSQL_USER=spotweb
     - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
     - /mnt/Docker/Spotweb/mariadb:/config
    ports:
     - 3306:3306
